name: aidnix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  otp_text_field: ^1.1.3
  country_code_picker: ^3.0.0
  pinput: ^4.0.0
  readmore: ^3.0.0
  google_maps_flutter:
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.5
  location: ^6.0.1
  device_info_plus: 9.1.2
  package_info_plus: ^8.0.0
  firebase_messaging: ^14.7.21
  firebase_core: 2.29.0
#  sim_data_plus: ^0.1.4
  permission_handler: ^11.3.1
  simnumber: ^0.0.12
  geolocator: ^11.0.0
  file_picker: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
